"""first migration

Revision ID: e06ccefb7679
Revises: 
Create Date: 2025-09-16 17:50:31.452894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06ccefb7679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=False),
    sa.Column('to', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'HTML', name='emailcontenttype'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'CANCELED', 'FAILED', name='emailstatus'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
